package vn.sportscourt.courtmate.b2b.entity;

import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;
import vn.sportscourt.courtmate.b2b.enums.VenueStatus;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Entity
@Table(name = "venues")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Venue {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id")
    Users owner;

    @Column(nullable = false)
    String name;

    @Column(unique = true)
    String slug; // auto-generated by DB trigger

    String description;
    String phone;
    String email;

    @Column(nullable = false)
    String address;

    @Column(name = "lat")
    BigDecimal lat;

    @Column(name = "lng")
    BigDecimal lng;

    /**
     * JSONB: {"weekday":{"open":"06:00","close":"22:00"},"weekend":{...}}
     */
    @Type(JsonBinaryType.class)
    @Column(name = "working_hours", columnDefinition = "jsonb")
    Map<String, Object> workingHours;

    /**
     * JSONB: ["parking","shower","locker","cafe"]
     */
    @Type(JsonBinaryType.class)
    @Column(columnDefinition = "jsonb")
    List<String> amenities;

    /**
     * JSONB: {"bank_name":"...","account_number":"...","account_holder":"..."}
     * Sensitive — never serialized to B2C responses.
     */
    @Type(JsonBinaryType.class)
    @Column(name = "bank_account", columnDefinition = "jsonb")
    private Map<String, Object> bankAccount;

    @Builder.Default
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(name = "status")
    VenueStatus status = VenueStatus.active;

    @Builder.Default
    @Column(name = "rating_avg")
    BigDecimal ratingAvg = BigDecimal.ZERO;

    @Builder.Default
    @Column(name = "total_reviews")
    Integer totalReviews = 0;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    OffsetDateTime updatedAt;

    @OneToMany(mappedBy = "venue", cascade = CascadeType.ALL, orphanRemoval = true)
    List<Court> courts;
}
